DESC EMPLOYEES;

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID, EMPLOYEE_ID, HIRE_DATE, COMMISSION_PCT, JOB_ID, MANAGER_ID)
VALUES ('eman', 'abdelwhab', 100000, 2, 4, SYSDATE, 0.30, 'AI', 200);

DESC DEPARTMENTS;

INSERT INTO DEPARTMENTS
VALUES (3,'CS',200, 1);

--insert null values
INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES (4,'is');

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID,LOCATION_ID)
VALUES (6,'As',NULL,NULL);

INSERT INTO DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES (&dept_id,&dept_name);

CREATE TABLE xx_emp
(empno NUMBER,
fname VARCHAR2(100),
SALARY number);

INSERT INto xx_emp(empno,fname,SALARY)
SELECT EMPLOYEE_ID,FIRST_NAME,SALARY
FROM EMPLOYEES;

SELECT * FROM xx_emp;