--cross join
SELECT
EMPLOYEES.EMPLOYEE_ID,
EMPLOYEES.FIRST_NAME,
DEPARTMENTS.DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
cross join DEPARTMENTS
ORDER by EMPLOYEE_ID;

CREATE TABLE location (
    location_id    NUMBER PRIMARY KEY,
    street_address VARCHAR2(255),
    postal_code    VARCHAR2(20),
    city           VARCHAR2(100),
    state_province VARCHAR2(100),
    country_id     VARCHAR2(2) -- Assuming a two-letter country code
);
-- Inserting data into the location table
INSERT INTO location (location_id, street_address, postal_code, city, state_province, country_id)
VALUES
    -- (1, '123 Main St', '12345', 'City1', 'State1', 'US');
    -- (2, '456 Oak St', '54321', 'City2', 'State2', 'CA');
    (200, '789 Pine St', '67890', 'City3', 'State3', 'IN');

--natural join
SELECT DEPARTMENTS.DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME,LOCATION_ID, location.city
FROM DEPARTMENTS
natural join location;

--join using clause to join based on selected column
SELECT
EMPLOYEES.EMPLOYEE_ID,
EMPLOYEES.FIRST_NAME,
DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES join
DEPARTMENTS
USING (department_id)
ORDER by EMPLOYEE_ID;

--join on
SELECT
EMPLOYEES.EMPLOYEE_ID,
EMPLOYEES.FIRST_NAME,
DEPARTMENTS.DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS 
ON (EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID)
ORDER by EMPLOYEE_ID;

SELECT emp.EMPLOYEE_ID, emp.FIRST_NAME, emp.SALARY, grades.job_level
FROM EMPLOYEES emp JOIN
JOB_GRADES grades
on emp.SALARY between GRADES.LOWEST_SAL And GRADES.HIGHEST_SAL;

SELECT worker.EMPLOYEE_ID,
worker.FIRST_NAME,
worker.manager_id,
manager.FIRST_NAME
FROM EMPLOYEES worker JOIN EMPLOYEES MANAGER
on(worker.MANAGER_ID=manager.EMPLOYEE_ID);

SELECT 
emp.EMPLOYEE_ID,
emp.FIRST_NAME,
emp.DEPARTMENT_ID,
dept.DEPARTMENT_NAME,
dept.LOCATION_ID,
loc.city
from EMPLOYEES emp
join DEPARTMENTS DEPT
on(emp.DEPARTMENT_ID = DEPT.DEPARTMENT_ID) 
join LOCATION LOC
on (dept.LOCATION_ID=LOC.LOCATION_ID)
order by EMP.EMPLOYEE_ID;


--left outer join
SELECT
EMPLOYEES.EMPLOYEE_ID,
EMPLOYEES.FIRST_NAME,
DEPARTMENTS.DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
left outer JOIN DEPARTMENTS
on(EMPLOYEES.EMPLOYEE_ID=DEPARTMENTS.DEPARTMENT_ID)
order by EMPLOYEE_ID;

--right outer join
SELECT
EMPLOYEES.EMPLOYEE_ID,
EMPLOYEES.FIRST_NAME,
DEPARTMENTS.DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
RIGHT outer JOIN DEPARTMENTS
on(EMPLOYEES.EMPLOYEE_ID=DEPARTMENTS.DEPARTMENT_ID)
order by EMPLOYEE_ID;

--full outer join
SELECT
EMPLOYEES.EMPLOYEE_ID,
EMPLOYEES.FIRST_NAME,
DEPARTMENTS.DEPARTMENT_ID,
DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
FULL outer JOIN DEPARTMENTS
on(EMPLOYEES.EMPLOYEE_ID=DEPARTMENTS.DEPARTMENT_ID)
order by EMPLOYEE_ID;
