-- max min
SELECT SALARY
FROM EMPLOYEES
order by SALARY desc;

SELECT MAX(SALARY), MIN(SALARY)
from EMPLOYEES;

SELECT MAX(FIRST_NAME), MIN(FIRST_NAME)
from EMPLOYEES;

SELECT MAX(HIRE_DATE), MIN(HIRE_DATE)
from EMPLOYEES;

SELECT sum(SALARY), avg(SALARY)
from EMPLOYEES;

SELECT * FROM   EMPLOYEES;
SELECT count(*) FROM   EMPLOYEES;

SELECT * FROM   EMPLOYEES;
SELECT count(1) FROM   EMPLOYEES;

SELECT COUNT(DEPARTMENT_ID)
FROM EMPLOYEES; --null not counted

SELECT COUNT(DISTINCT commission_pct)
FROM EMPLOYEES;

SELECT COUNT(NVL(commission_pct,0))
FROM EMPLOYEES;