--single subquery

SELECT SALARY from employees where FIRST_NAME='Jane';

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
where SALARY >(SELECT SALARY from employees where FIRST_NAME='Jane');

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
where SALARY =(SELECT SALARY from employees where FIRST_NAME='Jane');

SELECT * from EMPLOYEES
WHERE SALARY >(SELECT SALARY FROM EMPLOYEES where DEPARTMENT_ID=1);

SELECT DEPARTMENT_ID,COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) >(SELECT COUNT(1)
                            FROM EMPLOYEES
                            where DEPARTMENT_ID=10);


--multiple subquery
SELECT SALARY FROM EMPLOYEES where DEPARTMENT_ID=1;

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
where SALARY IN(SELECT SALARY FROM EMPLOYEES where DEPARTMENT_ID=1);

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
where SALARY >= any(SELECT SALARY FROM EMPLOYEES where DEPARTMENT_ID=1);


SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
where SALARY >= all(SELECT SALARY FROM EMPLOYEES where DEPARTMENT_ID=1);

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
where SALARY NOT IN(SELECT SALARY FROM EMPLOYEES where DEPARTMENT_ID=1);

SELECT SALARY FROM EMPLOYEES where MANAGER_ID is NULL;

SELECT * from EMPLOYEES
where MANAGER_ID in (100,101,NULL);

SELECT * from EMPLOYEES
where MANAGER_ID not in (100,101,NULL);

--Exists /not Exists
SELECT * FROM
DEPARTMENTS dept
where EXISTS(SELECT DEPARTMENT_ID FROM EMPLOYEES emp WHERE emp.DEPARTMENT_ID=DEPT.DEPARTMENT_ID);

SELECT * FROM
DEPARTMENTS dept
where not EXISTS(SELECT DEPARTMENT_ID FROM EMPLOYEES emp WHERE emp.DEPARTMENT_ID=DEPT.DEPARTMENT_ID);
