UPDATE EMPLOYEES
set SALARY=5000
WHERE EMPLOYEE_ID=1;

SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
set SALARY=5500
WHERE FIRST_NAME='Bob';

UPDATE EMPLOYEES 
SET SALARY=7000,DEPARTMENT_ID=3
WHERE EMPLOYEE_ID=3;

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
where EMPLOYEE_ID in (1,2);

UPDATE EMPLOYEES
SET SALARY=(SELECT SALARY FROM EMPLOYEEs where EMPLOYEE_ID in (2))
where EMPLOYEE_ID=1;

SELECT * FROM EMPLOYEES
where EMPLOYEE_ID in (1,2);




